// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkzajgypnopwgzjkzsjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJremFqZ3lwbm9wd2d6amt6c2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNDgzMTEsImV4cCI6MjA2NjYyNDMxMX0.AgmpgyEsPeqEufgFRuwFYBLurcFRux73bN9lBV5Yn2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);