// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfxxgirjweejmjkuqagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeHhnaXJqd2Vlam1qa3VxYWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODEyNDMsImV4cCI6MjA2NTA1NzI0M30.hc-yFVDh6lxrFbpguxqfOu-tPcY0ihh4YWjMDDzPHoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);