// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbywjahzaflbjmrbechl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRieXdqYWh6YWZsYmptcmJlY2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDk2NjQsImV4cCI6MjA2NjUyNTY2NH0.wVCb9pZ3UdbdoSvtmqHFI129L60UmyMszDoJK1arfBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});